version: 2
project_name: ikea-dirigera-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: ikea-dirigera-cli
    main: ./main.go
    binary: ikea
    ldflags:
      - -s -w
      - -X github.com/salex-org/ikea-dirigera-client/cmd.version={{ .Version }}
      - -X github.com/salex-org/ikea-dirigera-client/cmd.commit={{ .Commit }}
      - -X github.com/salex-org/ikea-dirigera-client/cmd.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: salex-org
    name: ikea-dirigera-client
  draft: false
  prerelease: false

homebrew_casks:
  - name: ikea-dirigera-cli
    homepage: "https://github.com/salex-org/ikea-dirigera-client"
    description: "A CLI for the IKEA DIRIGERA Smart-Home-Hub"
    license: MIT
    binaries:
      - ikea
    repository:
      owner: salex-org
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "v{{ incpatch .Version }}-snapshot"
